/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elcellervins;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.util.ArrayList;
import java.util.SortedSet;
import java.util.TreeSet;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.border.Border;

/**
 *
 * @author Reixowtf
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private Container pActive, pParent;
    private String matchSpace;
    private ArrayList<Component> colorejarBorders;
    private Border defaultBorder;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        pActive = this.getContentPane();
        pParent = this.getContentPane();
        matchSpace = "^\\s*$";
        colorejarBorders = new ArrayList<>();
        defaultBorder = jTA_producteAtrAromes.getBorder();
        jL_campsBuits.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jCB_producteIntensitatAroma5 = new javax.swing.JComboBox();
        jP_principal = new javax.swing.JPanel();
        jB_editarProducte = new javax.swing.JButton();
        jB_obtenirCataleg = new javax.swing.JButton();
        jB_nouProducte = new javax.swing.JButton();
        jP_producte = new javax.swing.JPanel();
        jB_tornar = new javax.swing.JButton();
        jP_nouProducte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTF_producteNom = new javax.swing.JTextField();
        jTF_productorNom = new javax.swing.JTextField();
        jTF_producteRegio = new javax.swing.JTextField();
        jSP_varietatRaim = new javax.swing.JScrollPane();
        jTA_varietatRaim = new javax.swing.JTextArea();
        jTF_producteAlcohol = new javax.swing.JTextField();
        jTF_producteAnyCollita = new javax.swing.JTextField();
        jTF_productePreu = new javax.swing.JTextField();
        jTF_producteDataCata = new javax.swing.JTextField();
        jB_afegirAtributsProducte = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jCB_producteTipusVi = new javax.swing.JComboBox();
        jP_editarProducte = new javax.swing.JPanel();
        jB_editarProduct = new javax.swing.JButton();
        jCB_producteNom = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jCB_producteAtrEditar = new javax.swing.JComboBox();
        jP_atributEditarProducte = new javax.swing.JPanel();
        jP_atributEditarProducteTF = new javax.swing.JPanel();
        jTF_AEP = new javax.swing.JTextField();
        jP_atributEditarProducteTA = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jP_atributEditarProducteCB = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jP_afegirAtributsProducte = new javax.swing.JPanel();
        jCB_producteAtrPofunditat = new javax.swing.JComboBox();
        jCB_producteAtrSecDols = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jB_generarProducte = new javax.swing.JButton();
        jCB_producteAtrTonalitat = new javax.swing.JComboBox();
        jCB_producteAtrNetedat = new javax.swing.JComboBox();
        jCB_producteAtrIntensitatAroma = new javax.swing.JComboBox();
        jCB_producteAtrCos = new javax.swing.JComboBox();
        jCB_producteAtrAcidez = new javax.swing.JComboBox();
        jCB_producteAtrIntensitaSabor = new javax.swing.JComboBox();
        jCB_producteAtrTempsBoca = new javax.swing.JComboBox();
        jSP_producteAtrAromes = new javax.swing.JScrollPane();
        jTA_producteAtrAromes = new javax.swing.JTextArea();
        jSP_producteAtrConclusions = new javax.swing.JScrollPane();
        jTA_producteAtrConclusions = new javax.swing.JTextArea();
        jSP_producteAtrSabors = new javax.swing.JScrollPane();
        jTA_producteAtrSabors = new javax.swing.JTextArea();
        jL_campsBuits = new javax.swing.JLabel();

        jCB_producteIntensitatAroma5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jB_editarProducte.setText("Editar Producte");
        jB_editarProducte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editarProducteActionPerformed(evt);
            }
        });

        jB_obtenirCataleg.setText("Obtenir Cataleg");
        jB_obtenirCataleg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_obtenirCatalegActionPerformed(evt);
            }
        });

        jB_nouProducte.setText("Nou Producte");
        jB_nouProducte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_nouProducteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_principalLayout = new javax.swing.GroupLayout(jP_principal);
        jP_principal.setLayout(jP_principalLayout);
        jP_principalLayout.setHorizontalGroup(
            jP_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_principalLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jP_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jB_editarProducte, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_nouProducte, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addComponent(jB_obtenirCataleg, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jP_principalLayout.setVerticalGroup(
            jP_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_principalLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jP_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_nouProducte, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_obtenirCataleg, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jB_editarProducte, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        getContentPane().add(jP_principal, "card3");

        jB_tornar.setText("Tornar");
        jB_tornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_tornarActionPerformed(evt);
            }
        });

        jP_nouProducte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jP_nouProducte, org.jdesktop.beansbinding.ObjectProperty.create(), jP_nouProducte, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nom del vi:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Productor:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Regió:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Alcohol:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Varietat de raïm:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("*Any collita:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("*Preu:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("*Data de la cata:");

        jTF_producteNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTF_productorNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTF_producteRegio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTA_varietatRaim.setColumns(20);
        jTA_varietatRaim.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTA_varietatRaim.setRows(5);
        jSP_varietatRaim.setViewportView(jTA_varietatRaim);

        jTF_producteAlcohol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTF_producteAnyCollita.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTF_productePreu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTF_producteDataCata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jB_afegirAtributsProducte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jB_afegirAtributsProducte.setText("Afegir atributs del Producte");
        jB_afegirAtributsProducte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_afegirAtributsProducteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tipus de Vi:");

        jCB_producteTipusVi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCB_producteTipusVi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Negre", "Blanc", "Rosat", "Espumós" }));
        jCB_producteTipusVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_producteTipusViActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_nouProducteLayout = new javax.swing.GroupLayout(jP_nouProducte);
        jP_nouProducte.setLayout(jP_nouProducteLayout);
        jP_nouProducteLayout.setHorizontalGroup(
            jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_nouProducteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_nouProducteLayout.createSequentialGroup()
                        .addGroup(jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTF_producteRegio)
                            .addComponent(jTF_producteNom)
                            .addComponent(jTF_productorNom)
                            .addComponent(jSP_varietatRaim, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(jTF_producteAlcohol, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCB_producteTipusVi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel3))
                .addGap(79, 79, 79)
                .addGroup(jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_nouProducteLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(22, 22, 22)
                        .addComponent(jTF_producteDataCata, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                    .addGroup(jP_nouProducteLayout.createSequentialGroup()
                        .addGroup(jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addGroup(jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_productePreu)
                            .addComponent(jTF_producteAnyCollita))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_nouProducteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jB_afegirAtributsProducte, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jP_nouProducteLayout.setVerticalGroup(
            jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_nouProducteLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_producteNom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jTF_producteAnyCollita, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTF_productorNom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTF_productePreu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_producteRegio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jCB_producteTipusVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSP_varietatRaim, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jP_nouProducteLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)))
                .addGap(27, 27, 27)
                .addGroup(jP_nouProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_producteAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jTF_producteDataCata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jB_afegirAtributsProducte, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jB_editarProduct.setText("Editar Producte");

        jCB_producteNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nom:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Atribut a editar:");

        jCB_producteAtrEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCB_producteAtrEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_producteAtrEditarActionPerformed(evt);
            }
        });

        jP_atributEditarProducte.setLayout(new java.awt.CardLayout());

        jTF_AEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jP_atributEditarProducteTFLayout = new javax.swing.GroupLayout(jP_atributEditarProducteTF);
        jP_atributEditarProducteTF.setLayout(jP_atributEditarProducteTFLayout);
        jP_atributEditarProducteTFLayout.setHorizontalGroup(
            jP_atributEditarProducteTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_atributEditarProducteTFLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jTF_AEP, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jP_atributEditarProducteTFLayout.setVerticalGroup(
            jP_atributEditarProducteTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_atributEditarProducteTFLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTF_AEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jP_atributEditarProducte.add(jP_atributEditarProducteTF, "card2");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jP_atributEditarProducteTALayout = new javax.swing.GroupLayout(jP_atributEditarProducteTA);
        jP_atributEditarProducteTA.setLayout(jP_atributEditarProducteTALayout);
        jP_atributEditarProducteTALayout.setHorizontalGroup(
            jP_atributEditarProducteTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_atributEditarProducteTALayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jP_atributEditarProducteTALayout.setVerticalGroup(
            jP_atributEditarProducteTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_atributEditarProducteTALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jP_atributEditarProducte.add(jP_atributEditarProducteTA, "card3");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jP_atributEditarProducteCBLayout = new javax.swing.GroupLayout(jP_atributEditarProducteCB);
        jP_atributEditarProducteCB.setLayout(jP_atributEditarProducteCBLayout);
        jP_atributEditarProducteCBLayout.setHorizontalGroup(
            jP_atributEditarProducteCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_atributEditarProducteCBLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jP_atributEditarProducteCBLayout.setVerticalGroup(
            jP_atributEditarProducteCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_atributEditarProducteCBLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jP_atributEditarProducte.add(jP_atributEditarProducteCB, "card4");

        javax.swing.GroupLayout jP_editarProducteLayout = new javax.swing.GroupLayout(jP_editarProducte);
        jP_editarProducte.setLayout(jP_editarProducteLayout);
        jP_editarProducteLayout.setHorizontalGroup(
            jP_editarProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_editarProducteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jB_editarProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jP_editarProducteLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jP_editarProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jP_editarProducteLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jCB_producteNom, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_editarProducteLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jCB_producteAtrEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))))
            .addGroup(jP_editarProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_editarProducteLayout.createSequentialGroup()
                    .addContainerGap(61, Short.MAX_VALUE)
                    .addComponent(jP_atributEditarProducte, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(177, Short.MAX_VALUE)))
        );
        jP_editarProducteLayout.setVerticalGroup(
            jP_editarProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_editarProducteLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jP_editarProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_producteNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addGroup(jP_editarProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jCB_producteAtrEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(jB_editarProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jP_editarProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_editarProducteLayout.createSequentialGroup()
                    .addContainerGap(148, Short.MAX_VALUE)
                    .addComponent(jP_atributEditarProducte, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(144, Short.MAX_VALUE)))
        );

        jCB_producteAtrPofunditat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCB_producteAtrSecDols.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Profunditat:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Netedat:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tonalitat:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("*Aromes:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Sec/Dolç:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Cos:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Acidez:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Intensitat de l'aroma:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Temps en boca:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Intensitat del sabor:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("*Conclusions/Opinions:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("*Sabors:");

        jB_generarProducte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jB_generarProducte.setText("Guardar Producte");
        jB_generarProducte.setActionCommand("");
        jB_generarProducte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_generarProducteActionPerformed(evt);
            }
        });

        jCB_producteAtrTonalitat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCB_producteAtrNetedat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCB_producteAtrIntensitatAroma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCB_producteAtrCos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCB_producteAtrAcidez.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCB_producteAtrIntensitaSabor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCB_producteAtrTempsBoca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTA_producteAtrAromes.setColumns(20);
        jTA_producteAtrAromes.setRows(5);
        jSP_producteAtrAromes.setViewportView(jTA_producteAtrAromes);

        jTA_producteAtrConclusions.setColumns(20);
        jTA_producteAtrConclusions.setRows(5);
        jSP_producteAtrConclusions.setViewportView(jTA_producteAtrConclusions);

        jTA_producteAtrSabors.setColumns(20);
        jTA_producteAtrSabors.setRows(5);
        jSP_producteAtrSabors.setViewportView(jTA_producteAtrSabors);

        javax.swing.GroupLayout jP_afegirAtributsProducteLayout = new javax.swing.GroupLayout(jP_afegirAtributsProducte);
        jP_afegirAtributsProducte.setLayout(jP_afegirAtributsProducteLayout);
        jP_afegirAtributsProducteLayout.setHorizontalGroup(
            jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_afegirAtributsProducteLayout.createSequentialGroup()
                .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_afegirAtributsProducteLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)))
                        .addGap(26, 26, 26)
                        .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCB_producteAtrPofunditat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCB_producteAtrTonalitat, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCB_producteAtrNetedat, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jP_afegirAtributsProducteLayout.createSequentialGroup()
                        .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_afegirAtributsProducteLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel18))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_afegirAtributsProducteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)))
                        .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSP_producteAtrAromes, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(jSP_producteAtrConclusions)
                            .addComponent(jCB_producteAtrIntensitatAroma, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_afegirAtributsProducteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jB_generarProducte, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_afegirAtributsProducteLayout.createSequentialGroup()
                        .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_afegirAtributsProducteLayout.createSequentialGroup()
                                .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCB_producteAtrIntensitaSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_producteAtrTempsBoca, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_producteAtrAcidez, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_producteAtrCos, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_producteAtrSecDols, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 90, Short.MAX_VALUE))
                            .addComponent(jSP_producteAtrSabors, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jP_afegirAtributsProducteLayout.setVerticalGroup(
            jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_afegirAtributsProducteLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_producteAtrPofunditat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(jCB_producteAtrSecDols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_producteAtrTonalitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jCB_producteAtrCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jCB_producteAtrNetedat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jCB_producteAtrAcidez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_producteAtrIntensitatAroma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jCB_producteAtrIntensitaSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSP_producteAtrAromes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel22)
                    .addComponent(jSP_producteAtrSabors, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_afegirAtributsProducteLayout.createSequentialGroup()
                        .addGroup(jP_afegirAtributsProducteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jCB_producteAtrTempsBoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jB_generarProducte, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSP_producteAtrConclusions, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)))
        );

        jL_campsBuits.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_campsBuits.setForeground(new java.awt.Color(255, 0, 0));
        jL_campsBuits.setText("*Falten camps per omplir.");

        javax.swing.GroupLayout jP_producteLayout = new javax.swing.GroupLayout(jP_producte);
        jP_producte.setLayout(jP_producteLayout);
        jP_producteLayout.setHorizontalGroup(
            jP_producteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_producteLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jL_campsBuits, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(jB_tornar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jP_producteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jP_producteLayout.createSequentialGroup()
                    .addComponent(jP_nouProducte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 17, Short.MAX_VALUE)))
            .addGroup(jP_producteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jP_producteLayout.createSequentialGroup()
                    .addComponent(jP_editarProducte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
            .addGroup(jP_producteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jP_producteLayout.createSequentialGroup()
                    .addComponent(jP_afegirAtributsProducte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 17, Short.MAX_VALUE)))
        );
        jP_producteLayout.setVerticalGroup(
            jP_producteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_producteLayout.createSequentialGroup()
                .addContainerGap(519, Short.MAX_VALUE)
                .addGroup(jP_producteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_tornar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_campsBuits))
                .addGap(25, 25, 25))
            .addGroup(jP_producteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jP_producteLayout.createSequentialGroup()
                    .addComponent(jP_nouProducte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 98, Short.MAX_VALUE)))
            .addGroup(jP_producteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jP_producteLayout.createSequentialGroup()
                    .addComponent(jP_editarProducte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 95, Short.MAX_VALUE)))
            .addGroup(jP_producteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jP_producteLayout.createSequentialGroup()
                    .addComponent(jP_afegirAtributsProducte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 97, Short.MAX_VALUE)))
        );

        getContentPane().add(jP_producte, "card4");

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_obtenirCatalegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_obtenirCatalegActionPerformed
        changeLayout(null);

    }//GEN-LAST:event_jB_obtenirCatalegActionPerformed

    private void jB_nouProducteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_nouProducteActionPerformed
        changeLayout(pActive = jP_nouProducte);
        jTF_producteNom.requestFocus();
        pParent = jP_nouProducte;
    }//GEN-LAST:event_jB_nouProducteActionPerformed

    private void jB_tornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_tornarActionPerformed
        //Expressió regular per verificar que les dades entrades son correctes (només lletres i espais)
        //^((\\w)+[\\s]?)+$
        if (campsOmplerts()) {
            int opcio = JOptionPane.showConfirmDialog(null, "Segur que voleu tornar?\nS'esborraran les dades entrades.", "Tornar", JOptionPane.YES_NO_OPTION);
            if (opcio == JOptionPane.YES_OPTION) {
                natejarPantalla();
                if (jP_nouProducte.isShowing() || jP_editarProducte.isShowing()) {
                    this.setContentPane(jP_principal);
                    jP_principal.setVisible(true);
                    pActive = jP_principal;
                } else {
                    changeLayout(pActive = pParent);
                }
            }
        } else {
            natejarPantalla();
            if (jP_nouProducte.isShowing() || jP_editarProducte.isShowing()) {
                this.setContentPane(jP_principal);
                jP_principal.setVisible(true);
                pActive = jP_principal;
            } else {
                changeLayout(pActive = pParent);
            }
        }
    }//GEN-LAST:event_jB_tornarActionPerformed

    private void jB_editarProducteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editarProducteActionPerformed
        jCB_producteAtrEditar.setModel(new DefaultComboBoxModel(obtenirLabels().toArray()));
        jP_atributEditarProducteTA.setVisible(false);
        jP_atributEditarProducteCB.setVisible(false);
        jP_atributEditarProducteTF.setVisible(false);
        jP_atributEditarProducte.setVisible(false);
        changeLayout(pActive = jP_editarProducte);
        pParent = jB_editarProduct;
    }//GEN-LAST:event_jB_editarProducteActionPerformed
    
    private void jB_afegirAtributsProducteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_afegirAtributsProducteActionPerformed
        if (campsOmplerts(new Component[]{jTF_producteDataCata, jTF_producteAnyCollita, jTF_productePreu})) {
            jL_campsBuits.setVisible(false);
            changeLayout(pActive = jP_afegirAtributsProducte);
        } else {
            colorejarCamps(colorejarBorders, BorderFactory.createLineBorder(Color.RED));
        }
    }//GEN-LAST:event_jB_afegirAtributsProducteActionPerformed

    private void jB_generarProducteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_generarProducteActionPerformed
        if (campsOmplerts(new Component[]{jSP_producteAtrAromes, jSP_producteAtrConclusions, jSP_producteAtrSabors})) {
            int opcio = JOptionPane.showConfirmDialog(null, "Segur que vols guardar aquest producte?", "Guardar", JOptionPane.YES_NO_OPTION);
            if (opcio == JOptionPane.YES_OPTION) {
                //TODO: Fer tot el guardat de dades
                natejarPantalla();
                changeLayout(pActive = pParent);
                natejarPantalla();
                System.out.println("guardat");
            }
        } else {
            colorejarCamps(colorejarBorders, BorderFactory.createLineBorder(Color.RED));
        }
    }//GEN-LAST:event_jB_generarProducteActionPerformed

    private void jCB_producteTipusViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_producteTipusViActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_producteTipusViActionPerformed

    private void jCB_producteAtrEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_producteAtrEditarActionPerformed
        System.out.println(jCB_producteAtrEditar.getSelectedItem());
    }//GEN-LAST:event_jCB_producteAtrEditarActionPerformed

    private SortedSet<String> obtenirLabels(){
        SortedSet<String> cTLabel = new TreeSet<>();
        for (Component c : jP_afegirAtributsProducte.getComponents()) {
            if (c.getClass() == JLabel.class) {
                if (!(((JLabel) c).getText().equalsIgnoreCase("") || ((JLabel) c).getText().equalsIgnoreCase(null))) {
                    if (((JLabel) c).getText().substring(0, 1).equalsIgnoreCase("*")) {
                        cTLabel.add(((JLabel) c).getText().substring(1, ((JLabel) c).getText().length() - 1));
                    } else {
                        cTLabel.add(((JLabel) c).getText().substring(0, ((JLabel) c).getText().length() - 1));
                    }
                }
            }
        }
        for (Component c : jP_nouProducte.getComponents()) {
            if (c.getClass() == JLabel.class) {
                if (!(((JLabel) c).getText().equalsIgnoreCase("") || ((JLabel) c).getText().equalsIgnoreCase(null))) {
                    if (((JLabel) c).getText().substring(0, 1).equalsIgnoreCase("*")) {
                        cTLabel.add(((JLabel) c).getText().substring(1, ((JLabel) c).getText().length() - 1));
                    } else {
                        cTLabel.add(((JLabel) c).getText().substring(0, ((JLabel) c).getText().length() - 1));
                    }
                }
            }
        }
        return cTLabel;
    }
    
    //Natejar tots els valors entrats
    private void natejarPantalla() {
        for (Component comp : pActive.getComponents()) {
            if (comp.getClass() == JLabel.class || comp.getClass() == JButton.class) {
                continue;
            } else if (comp.getClass() == JTextField.class) {
                ((JTextField) comp).setText("");
            } else if (comp.getClass() == JScrollPane.class) {
                for (Component cScroll : ((JScrollPane) comp).getViewport().getComponents()) {
                    if (cScroll.getClass() == JTextArea.class) {
                        ((JTextArea) cScroll).setText(null);
                    }
                }
            }
        }
        colorejarCamps(colorejarBorders, defaultBorder);
        colorejarBorders.clear();
    }

    //Comprovació de si totes les dades estan entrades en tots els camps.
    private boolean campsOmplerts() {
        for (Component comp : pActive.getComponents()) {
            if (comp.getClass() == JLabel.class || comp.getClass() == JButton.class) {
                continue;
            } else if (comp.getClass() == JTextField.class) {
                if (!((JTextField) comp).getText().matches(matchSpace)) {
                    return true;
                }
            } else if (comp.getClass() == JScrollPane.class) {
                for (Component cScroll : ((JScrollPane) comp).getViewport().getComponents()) {
                    if (cScroll.getClass() == JTextArea.class) {
                        if (!(((JTextArea) cScroll).getText()).matches(matchSpace)) {
                            return true;
                        }
                    }
                }
            }
        }
        return false;
    }

    //El paràmetre d'entrada és/són els components obtatius que no caldrà que estiguin marcats per continuar
    private boolean campsOmplerts(Component[] obtatiu) {
        colorejarCamps(colorejarBorders, defaultBorder);
        colorejarBorders.clear();
        boolean omplerts = true;
        for (Component comp : pActive.getComponents()) {
            if (obtatiu(obtatiu, comp) || comp.getClass() == JLabel.class || comp.getClass() == JButton.class) {
                continue;
            } else if (comp.getClass() == JTextField.class) {
                if (((JTextField) comp).getText().matches(matchSpace)) {
                    omplerts = false;
                    colorejarBorders.add(comp);
                }
            } else if (comp.getClass() == JScrollPane.class) {
                for (Component cScroll : ((JScrollPane) comp).getViewport().getComponents()) {
                    if (cScroll.getClass() == JTextArea.class) {
                        if ((((JTextArea) cScroll).getText()).matches(matchSpace)) {
                            omplerts = false;
                            colorejarBorders.add(cScroll);
                        }
                    }
                }
            }
        }
        return omplerts;
    }

    private boolean obtatiu(Component[] obtatiu, Component comp) {
        for (Component s : obtatiu) {
            if (s == comp) {
                return true;
            }
        }
        return false;
    }

    //Coloreja els camps que estan buits
    private void colorejarCamps(ArrayList<Component> c, Border bF) {
        for (Component comp : c) {
            if (comp.getClass() == JTextField.class) {
                ((JTextField) comp).setBorder(bF);
            } else if (comp.getClass() == JTextArea.class) {
                ((JTextArea) comp).setBorder(bF);
            }
        }
        if (bF.equals(defaultBorder)) {
            jL_campsBuits.setVisible(false);
        } else {
            jL_campsBuits.setVisible(true);
        }
    }

    private void changeLayout(Container c) {
        for (Component comp : jP_producte.getComponents()) {
            if (comp.equals(c)) {
                comp.setVisible(true);
            } else if (comp.getClass() == c.getClass()) {
                comp.setVisible(false);
            }
        }
        jP_producte.setVisible(true);
        this.setContentPane(jP_producte);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_afegirAtributsProducte;
    private javax.swing.JButton jB_editarProduct;
    private javax.swing.JButton jB_editarProducte;
    private javax.swing.JButton jB_generarProducte;
    private javax.swing.JButton jB_nouProducte;
    private javax.swing.JButton jB_obtenirCataleg;
    private javax.swing.JButton jB_tornar;
    private javax.swing.JComboBox jCB_producteAtrAcidez;
    private javax.swing.JComboBox jCB_producteAtrCos;
    private javax.swing.JComboBox jCB_producteAtrEditar;
    private javax.swing.JComboBox jCB_producteAtrIntensitaSabor;
    private javax.swing.JComboBox jCB_producteAtrIntensitatAroma;
    private javax.swing.JComboBox jCB_producteAtrNetedat;
    private javax.swing.JComboBox jCB_producteAtrPofunditat;
    private javax.swing.JComboBox jCB_producteAtrSecDols;
    private javax.swing.JComboBox jCB_producteAtrTempsBoca;
    private javax.swing.JComboBox jCB_producteAtrTonalitat;
    private javax.swing.JComboBox jCB_producteIntensitatAroma5;
    private javax.swing.JComboBox jCB_producteNom;
    private javax.swing.JComboBox jCB_producteTipusVi;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jL_campsBuits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jP_afegirAtributsProducte;
    private javax.swing.JPanel jP_atributEditarProducte;
    private javax.swing.JPanel jP_atributEditarProducteCB;
    private javax.swing.JPanel jP_atributEditarProducteTA;
    private javax.swing.JPanel jP_atributEditarProducteTF;
    private javax.swing.JPanel jP_editarProducte;
    private javax.swing.JPanel jP_nouProducte;
    private javax.swing.JPanel jP_principal;
    private javax.swing.JPanel jP_producte;
    private javax.swing.JScrollPane jSP_producteAtrAromes;
    private javax.swing.JScrollPane jSP_producteAtrConclusions;
    private javax.swing.JScrollPane jSP_producteAtrSabors;
    private javax.swing.JScrollPane jSP_varietatRaim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTA_producteAtrAromes;
    private javax.swing.JTextArea jTA_producteAtrConclusions;
    private javax.swing.JTextArea jTA_producteAtrSabors;
    private javax.swing.JTextArea jTA_varietatRaim;
    private javax.swing.JTextField jTF_AEP;
    private javax.swing.JTextField jTF_producteAlcohol;
    private javax.swing.JTextField jTF_producteAnyCollita;
    private javax.swing.JTextField jTF_producteDataCata;
    private javax.swing.JTextField jTF_producteNom;
    private javax.swing.JTextField jTF_productePreu;
    private javax.swing.JTextField jTF_producteRegio;
    private javax.swing.JTextField jTF_productorNom;
    private javax.swing.JTextArea jTextArea1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
